### PR TITLE
Add support for parsing YAML metadata.

### PR DESCRIPTION
**Pull request by chriskrycho**
It appears this is essentially an alternative implementation of @zackw's work in #3, which I only saw _after_ submitting the PR.

Cleary this is a desired feature. :wink:

### CODE REVIEW

**Comment by liob** [comment]
I have been pushing this issue on my todo list for a long time. @zackw, I am sorry for that.

The truth is, I really dislike all implementations presented so far. I do believe that metadata and content processing should be splitted up in different tasks in pelican. However, this will not hapen in the near future and there is a clear need for YAML support.

Therefore, I am asking you @zackw and @chriskrycho, which implementation do you like best?

I would favor @chriskrycho implementation. In my opinion it is not as elegant as @zackw's #3 but it is clear to read and does not use regex. I really dislike #4 conceptually.

**Comment by zackw** [comment]
I understand why you might not like #4 -- I'm not super happy with the output filter thing myself -- but it achieves something that can't reasonably be done any other way: it interprets Pandoc-flavor Markdown _inside_ text fields in metadata.  This is an essential feature for the site I am using this for (https://readings.owlfolio.org/), so if you reject that approach I am going to have to maintain a fork indefinitely :disappointed:  I am having a conversation with the Pandoc maintainers about adding a less clunky way to extract the metadata; see https://github.com/jgm/pandoc/issues/2019 .

I am indifferent between #3 and #5 since I would have to continue with #4 regardless; however, if you go with #5, please merge at least the documentation I wrote (corrected for _not_ aligning the "plain" metadata syntax with Pelican core) and the mechanism for only loading PyYAML if required (this is critical for backward compatibility with sites that don't expect PyYAML to be a dependency of this plugin).

**Comment by chriskrycho** [comment]
Note that I _do_ align plain metadata with Pelican core and gracefully degrade if PyYAML isn't available in #5—I agree that #3 is more elegant; I just wanted to be clear that this does _not_ fall down on normal metadata. That said, I'd be happy to integrate some of the better/more elegant features of the #3 solution into my own PR along the way (probably this upcoming weekend).

I've been following @zackw's conversation with the Pandoc folks at jgm/pandoc#2019 as well, and I think ultimately we want to replace _any_ of these solutions with that; hopefully it won't be too long in coming.

**Comment by liob** [comment]
I would prefer not to splinter the development. Therefore, I will merge pull request #4 when it is ready. However, this will only be a temporary solution. When jgm/pandoc#2019 is concluded, the code will be removed. I hope that this is a good solution for everyone.

**Comment by chriskrycho** [comment]
That seems eminently reasonable to me. Hopefully jgm/pandoc#2019 will get resolved in the next release of Pandoc!

**Pull request closed without merging**
